.gitignore
=> gitignore変更

Gemfile
=> gem全て追加しました！

config/routes.rb
=> routesファイル修正

app/controllers/customers/confirmations_controller.rb, app/controllers/customers/omniauth_callbacks_controller.rb, app/controllers/customers/passwords_controller.rb, app/controllers/customers/registrations_controller.rb, app/controllers/customers/sessions_controller.rb, app/controllers/customers/unlocks_controller.rb, app/views/customers/confirmations/new.html.erb, app/views/customers/mailer/confirmation_instructions.html.erb, app/views/customers/mailer/email_changed.html.erb, app/views/customers/mailer/password_change.html.erb, app/views/customers/mailer/reset_password_instructions.html.erb, app/views/customers/mailer/unlock_instructions.html.erb, app/views/customers/passwords/edit.html.erb, app/views/customers/passwords/new.html.erb, app/views/customers/registrations/edit.html.erb, app/views/customers/registrations/new.html.erb, app/views/customers/sessions/new.html.erb, app/views/customers/shared/_error_messages.html.erb, app/views/customers/shared/_links.html.erb, app/views/customers/unlocks/new.html.erb
=> 顧客側のログイン、登録画面

app/controllers/admins/confirmations_controller.rb, app/controllers/admins/omniauth_callbacks_controller.rb, app/controllers/admins/passwords_controller.rb, app/controllers/admins/registrations_controller.rb, app/controllers/admins/sessions_controller.rb, app/controllers/admins/unlocks_controller.rb, app/views/admins/confirmations/new.html.erb, app/views/admins/mailer/confirmation_instructions.html.erb, app/views/admins/mailer/email_changed.html.erb, app/views/admins/mailer/password_change.html.erb, app/views/admins/mailer/reset_password_instructions.html.erb, app/views/admins/mailer/unlock_instructions.html.erb, app/views/admins/passwords/edit.html.erb, app/views/admins/passwords/new.html.erb, app/views/admins/registrations/edit.html.erb, app/views/admins/registrations/new.html.erb, app/views/admins/sessions/new.html.erb, app/views/admins/shared/_error_messages.html.erb, app/views/admins/shared/_links.html.erb, app/views/admins/top.html.erb, app/views/admins/unlocks/new.html.erb, config/routes.rb
- AdminのDeviceControllerつくりました。
- Adminのログイン関連のViewつくりました。
- 上記に関連してroutes変更しました。
=> [Add]AdminのDeviceControllerおよびViewの設定

app/controllers/admins/sessions_controller.rb, app/models/address.rb, app/models/cart_item.rb, app/models/customer.rb, app/models/genre.rb, app/models/item.rb, app/models/order.rb, app/models/order_item.rb, app/views/admins/sessions/create.html.erb, app/views/admins/sessions/destroy.html.erb, app/views/admins/top.html.erb
=> [Add]各モデルにアソシエーションを追記

app/controllers/admins/items_controller.rb, app/controllers/customers/registrations_controller.rb, app/controllers/customers/sessions_controller.rb, app/models/item.rb, app/views/admins/items/new.html.erb
顧客ログイン後のページのルーティング変更、商品新規追加画面、itemモデルバリデート、enum設定、itemコントローラnew,create
=> 顧客ログイン後のページのルーティング変更、商品新規追加画面、itemモデルバリデート、enum設定、itemコントローラnew,create

app/controllers/admins/items_controller.rb, app/models/item.rb, app/views/admins/items/new.html.erb
商品画像のバリデーション削除
商品ジャンルをenum削除
admin/itemコントローラにif文追加
ジャンルselect文変更
=> itemモデル,バリデート,itemコントローラnew,create

app/controllers/admins/items_controller.rb, app/views/admins/items/index.html.erb, config/initializers/kaminari_config.rb
=> kaminari_config,itemコントローラindex,item/index.html

app/views/layouts/application.html.erb
=> ヘッダー完成しました

app/controllers/items_controller.rb, app/views/admins/customers/index.html.erb, app/views/items/index.html.erb, app/views/items/show.html.erb, config/routes.rb
=> [Add]カスタマの商品一覧/詳細など追加

app/views/customers/show.html.erb, config/routes.rb
=> ルートを調整。マイページが完成

app/controllers/customers_controller.rb, app/views/customers/edit.html.erb, app/views/customers/show.html.erb
嘘ですマイページのパスワード変更へのリンクがうまくいきません；；
=> マイページ、顧客情報編集ページ、カスタマーコントローラーが完成？

app/controllers/cart_items_controller.rb, app/views/cart_items/index.html.erb
=> cart_itemのindexを修正

app/controllers/cart_items_controller.rb, app/views/cart_items/index.html.erb, config/routes.rb
emptyアクションの追加、カートの中身を空にするものです。
destroyアクションに追加、カートの商品を一つ削除するものです。
routeを編集、collectionで2つ目のdeleteのemptyを有効にしました。
indexを編集
=> emptyアクションを追加

app/controllers/addresses_controller.rb, app/controllers/admins/customers_controller.rb, app/controllers/admins/genres_controller.rb, app/controllers/admins/items_controller.rb, app/controllers/admins/orders_controller.rb, app/controllers/admins/sessions_controller.rb, app/controllers/cart_items_controller.rb, app/controllers/customers/sessions_controller.rb, app/controllers/customers_controller.rb, app/controllers/items_controller.rb, app/controllers/order_items_controller.rb, app/controllers/orders_controller.rb, app/models/customer.rb, app/models/item.rb, app/views/admins/items/edit.html.erb, app/views/admins/items/show.html.erb, app/views/admins/orders/show.html.erb, app/views/cart_items/index.html.erb, app/views/items/index.html.erb, app/views/layouts/application.html.erb, db/seeds.rb
=> [Add]検索機能とflashメッセージ追加

app/views/cart_items/index.html.erb
ボタンのレイアウト
合計金額のレイアウト
カート内のアイテムが0の場合次のページへ進めない
=> [修正]コンフリクトによって起こったカートの変更点

app/models/cart_item.rb, app/views/cart_items/index.html.erb
=> [更新]カートの中身が0にならなくなりました

app/views/cart_items/info.html.erb
=> [修正]登録した住所入力時の空白を削除

app/views/cart_items/info.html.erb
JSのif文で登録済み住所が空白の時にラジヲボタンを非表示にしました。
サンキューakityan
=> [修正]登録済み住所が無いときにボタンを非表示に

app/models/genre.rb
[Fix]BooreanでバリデーションpresenceをかけたらダメなのでGenreモデル修正
=> Genreモデル修正
